version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - fastapiNet

    networks:
      - fastapiNet

networks:
  fastapiNet:
    driver: bridge
